name: Apptainer SYSMOIC-2024.2

on:
  push:
    branches: 
      - 'master'
    paths:
      - 'SYSMOIC-2024.2.def'
      - '.github/workflows/SYSMOIC-2024.2.apptainer.yml'
  pull_request:
    paths:
      - 'SYSMOIC-2024.2.def'
      - '.github/workflows/SYSMOIC-2024.2.apptainer.yml'

env:
  REGISTRY: oras://ghcr.io
  IMAGE_NAME: ${{ github.repository }}/SYSMOIC-2024.2-apptainer

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
    - uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.3.0
    - name: Build container
      run: |
        sudo -E apptainer build SYSMOIC-2024.2.sif ./SYSMOIC-2024.2.def
    - name: Log in to registry and deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | apptainer remote login -u ${{ github.actor }} --password-stdin ${{ env.REGISTRY }}
        echo "DEBUG"
        apptainer push SYSMOIC-2024.2.sif ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:master